version: "3.9"

services:

    seq:
        container_name: seq
        image: datalust/seq
        ports: 
            - "5341:80"
        environment:
            - ACCEPT_EULA=Y
        networks: 
            - masny-microservices-network

    data:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports: 
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrongPassword12!@
        volumes: 
            - sqldata:/var/opt/mssql 
        networks: 
            - masny-microservices-network
    
    messages:
        container_name: rabbitmq
        image: rabbitmq:3.9-management
        ports:
            - "15672:15672"
            - "5672:5672"
        hostname: "rabbitmq"
        environment:
            - RABBITMQ_ERLANG_COOKIE=Rand0mR4bbitMqCo0k1e
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
        networks: 
            - masny-microservices-network

    identity.api:
        container_name: identity
        build:
            context: ./src
            dockerfile: ./Masny.Microservices.Identity.Api/Dockerfile
        ports: 
            - "5011:80"
        environment:
            - EventBusSettings__Host=rabbitmq
            - EventBusSettings__Port=5672
            - EventBusSettings__VirtualHost=/
            - EventBusSettings__User=rabbitmq
            - EventBusSettings__Password=rabbitmq
        restart: on-failure
        networks: 
            - masny-microservices-network
        depends_on:
            - data
            
    profile.api:
        container_name: profile
        build:
            context: ./src
            dockerfile: ./Masny.Microservices.Profile.Api/Dockerfile
        ports:
            - "5046:80" 
        environment:
            - EventBusSettings__Host=rabbitmq
            - EventBusSettings__Port=5672
            - EventBusSettings__VirtualHost=/
            - EventBusSettings__User=rabbitmq
            - EventBusSettings__Password=rabbitmq
        restart: on-failure
        networks: 
            - masny-microservices-network
        depends_on:
            - data
            
    gateway.api:
        container_name: gateway
        build:
            context: ./src
            dockerfile: ./Masny.Microservices.Gateway.Main/Dockerfile
        ports:
            - "5053:80"
        restart: on-failure
        networks: 
            - masny-microservices-network
        depends_on:
            - seq

    webstatus:
        container_name: webstatus
        build:
            context: ./src
            dockerfile: ./Masny.Microservices.WebStatus/Dockerfile
        ports:
            - "5269:80"
        restart: on-failure
        networks: 
            - masny-microservices-network

networks:
    masny-microservices-network:

volumes:
    sqldata: